name: Cloud Weather Backfill (manual)

on:
  workflow_dispatch:
    inputs:
      hours:
        description: 'Quante ore di backfill (max 168 consigliato)'
        required: true
        default: '24'

permissions:
  contents: read

jobs:
  backfill:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ingest.txt

      - name: Run backfill
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SQLITE_PATH: ./data/weather.db
          ECOWITT_APP_KEY: ${{ secrets.ECOWITT_APP_KEY }}
          ECOWITT_API_KEY: ${{ secrets.ECOWITT_API_KEY }}
          ECOWITT_MAC: ${{ secrets.ECOWITT_MAC }}
          ECOWITT_TZ: Europe/Rome
          BACKFILL_HOURS: ${{ github.event.inputs.hours }}
        run: |
          python weather_ingest_ecowitt_cloud.py
