[server]
address = "localhost"
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#60a5fa"
backgroundColor = "#0b1220"
secondaryBackgroundColor = "#111827"
textColor = "#e5e7eb"
